name: Pyflakes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyflakes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Pyflakes
      run: |
        python -m pip install --upgrade pip
        pip install pyflakes

    - name: Run Pyflakes
      run: |
        pyflakes .
